NewsRssWeb/Models/NewsListViewModel.cs
using NewsRssWeb.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NewsRssWeb.Models
{
    public class NewsListViewModel
    {
        public IEnumerable<News> NewsList { get; set; }
        public SelectList GeneratorList { get; set; }
    }
}

NewsRssWeb/Controllers/HomeController.cs
using NewsRssWeb.Entity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NewsRssWeb.Controllers
{
    public class HomeController : Controller
    {
        ApplicationContext db = new ApplicationContext();

        public ActionResult AutocompleteSearch(string term)
        {
            var models = db.News.Where(a => a.Link.Contains(term))
                            .Select(a => new { value = a.Link })
                            .Distinct();

            return Json(models, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Index()
        {
            var news = db.News;
            return View(news);
        }

        public string GetData()
        {
            return JsonConvert.SerializeObject(db.News.First());
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

NewsRssWeb/Controllers/RssNewsController.cs
using NewsRssWeb.Entity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using PagedList;

namespace NewsRssWeb.Controllers
{
    public class RssNewsController : Controller
    {
        ApplicationContext db = new ApplicationContext();

        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page, int? generatorId)
        {
            ViewBag.GeneratorId = generatorId;
            ViewBag.CurrentSort = sortOrder;

            IQueryable<News> news = from s in db.News.Include(p => p.Generator)
                                    select s;
            if (generatorId != null && generatorId != 0)
            {
                news = news.Where(p => p.GeneratorId == generatorId);
            }

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            

            if (!String.IsNullOrEmpty(searchString))
            {
                news = news.Where(s => s.Title.Contains(searchString)
                                       || s.Title.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "date_Desc":
                    news = news.OrderByDescending(s => s.DatePublication);
                    break;
                case "Title":
                    news = news.OrderBy(s => s.Generator.Name);
                    break;
                default:
                    news = news.OrderBy(s => s.Id);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);           

            List<Generator> generator = db.Generators.ToList();
            generator.Insert(0, new Generator {  Name = "Все", Id = 0 });
            var ListGenerator = new SelectList(generator, "Id", "Name");
            ViewBag.ListGenerator = ListGenerator;
            return View(news.ToPagedList(pageNumber, pageSize));
        }
    }
}

NewsRssWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

NewsRssWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

NewsRssWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<html>
<head>
    <link href='@Url.Content("~/Content/themes/base/all.css")' rel="stylesheet" type="text/css" />

    <script src='@Url.Content("~/Scripts/jquery-1.10.2.min.js")' type="text/javascript"></script>
    <script src='@Url.Content("~/Scripts/jquery-ui-1.11.3.min.js")' type="text/javascript"></script>
</head>
<body>
    <input type="text" name="name" data-autocomplete-source='@Url.Action("AutocompleteSearch", "Home")' />
    <input type="submit" value="Поиск" />

    <script type="text/javascript">
        $(function () {
            $("[data-autocomplete-source]").each(function () {
                var target = $(this);
                target.autocomplete({ source: target.attr("data-autocomplete-source") });
            });
        });
    </script>
</body>
</html>

NewsRssWeb/Views/RssNews/Index.cshtml
@model PagedList.IPagedList<NewsRssWeb.Entity.News>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    /**/

    ViewBag.Title = "Новостная лента";
}

<h3>Новостная лента</h3>

@using (Html.BeginForm("Index", "RssNews", FormMethod.Get))
{
    <div><p>Источники ленты</p>@Html.DropDownList("GeneratorId", ViewBag.ListGenerator as SelectList, null, new { @class = "form-control" })</div>
    <br />
    <div>
        @Html.RadioButton("sortOrder", "date_Desc" )
        <span>Сортировать по дате</span>

        @Html.RadioButton("sortOrder", "Title" )
        <span>Сортировать по источнику</span>
    </div>
    <br />
    <input type="submit" value="Фильтр" class="btn btn-default" />
}

<table class="table">
    <tr>
        <td>Источник</td>
        <td>Название новости</td>
        <td>Описание новости</td>
        <td>Автор</td>
        <td>Дата публикации</td>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td><p>@item.Generator.Name</p></td>
            <td><a target="_blank" href="@item.Link"><p>@item.Title</p></a></td>
            <td><p>@item.Description</p></td>
            <td><p>@item.Author</p></td>
            <td><p>@item.DatePublication</p></td>
        </tr>
    }

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, ViewBag.GeneratorId }))

NewsRssWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Имя приложения", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Домашняя страница", "Index", "Home")</li>
                    <li>@Html.ActionLink("О программе", "About", "Home")</li>
                    <li>@Html.ActionLink("Контакт", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>